// Mocks generated by Mockito 5.0.17 from annotations
// in wheather_app/test/unit_tests/data/weather/mapper/weather_dto_to_weather_mapper_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:wheather_app/data/weather/mapper/weather_icon_mapper.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [WeatherIconMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherIconMapper extends _i1.Mock implements _i2.WeatherIconMapper {
  MockWeatherIconMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String call(String? iconPath) =>
      (super.noSuchMethod(Invocation.method(#call, [iconPath]), returnValue: '')
          as String);
}
