// Mocks generated by Mockito 5.0.17 from annotations
// in wheather_app/injectable/permissions/permissions_injectable.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler_platform_interface/permission_handler_platform_interface.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [PermissionWithService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionWithService extends _i1.Mock
    implements _i2.PermissionWithService {
  MockPermissionWithService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get value =>
      (super.noSuchMethod(Invocation.getter(#value), returnValue: 0) as int);
}
