// Mocks generated by Mockito 5.0.17 from annotations
// in wheather_app/test/unit_tests/domain/location/usecase/get_location_data_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:location/location.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wheather_app/domain/location/service/location_service.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeLocationData_0 extends _i1.Fake implements _i2.LocationData {}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i3.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.LocationData> getLocation() => (super.noSuchMethod(
          Invocation.method(#getLocation, []),
          returnValue: Future<_i2.LocationData>.value(_FakeLocationData_0()))
      as _i4.Future<_i2.LocationData>);
}
